### ISSUE TITLE
Handle noscript Better

### ISSUE THREAD

**Issue by rameshvarun** [rameshvarun/blog-cells#2]
Right now, with Javascript disabled, the code simply doesn't show at all. We should handle this better. Maybe let people create code cells in `<pre>` tags and transform them in-place into cells?

**Comment by Scepheo** [comment]
Alternatively, you could add CSS to make the `script` tags visible:

```css
script[type="text/notebook-cell"] {
  display: block;
}
```

This would also stop users from having to HTML-escape the content of `pre` tags.
